#!/bin/bash
# Help display functions for vb_tool

[[ -n "$_VB_HELP_LOADED" ]] && return 0
_VB_HELP_LOADED=1

show_help() {
    echo "Vastbase Script Tool (vb_tool)"
    echo ""
    echo "Usage Summary:"
    echo "  vb_tool <command> [options]"
    echo "  Example: vb_tool as <vb_pid>"
    echo ""
    echo "Available Commands:"
    echo "  analyze_log                          analyze database logs (slow queries or plans)"
	echo "  analyze_log_v2                       analyze database logs (slow queries) output html report (enhanced version)"
    echo "  as       [vb pid]                    display active session info"
    echo "  asp                                  analyze active session profile"
    echo "  collect_log                          collect logs for cluster or single node"
    echo "  dead_tups                            display dead tuples information"
    echo "  index_check                          display redundant/unused/unusable/novalid index"
    echo "  kill                                 terminate sessions by conditions"
    echo "  list                                 list vb_tool available script"
    echo "  lockchain                            display lock wait chain"
    echo "  lock_details                         display detailed lock information (holders & waiters)"
    echo "  lsds                                 list block devices and metadata"
    echo "  mem                                  display memory usage information"
    echo "  memhist                              display memory usage history"
    echo "  net                                  display network information"
    echo "  priv                                 display privileges for users/tables/databases/schemas"
	echo "  planbyline [file]                    analyze execution plan and output self-time by line"
    echo "  recover_table                        recover table data by ctid scan (skip corrupted rows)"
    echo "  redo        -f <log_file>            analyze redo log generate"
    echo "  relxlog [START_WAL] [END_WAL]        analyze WAL records for relations"
    echo "  repl                                 display Streaming Replication lag"
    echo "  slow                                 display top slow sql Information"
    echo "  sp       [guc]                       display guc parameter"
    echo "  sqlstat  [unique_query_id]           display sqlstat information"
	echo "  sqltext  [unique_query_id]           display sqltext from postgresql slow log"
	echo "  sqlhc    [unique_query_id]           display sql health check(include performance plan & sqlstat & tabstat)"
    echo "  ssh_setup                            setup SSH connectivity between hosts"
    echo "  st       [relname]                   display table or view"
    echo "  tabsize                              display top number size of tables(including all indexes)"
    echo "  tabstat                              display table statistics"
    echo "  tps                                  analyze TPS per 10 minutes"
    echo "  wdr_event                            display wdr top event information"
    echo "  wdr_summary                          display wdr workload information"
    echo "  wdr_topsql                           display wdr topsql information"
    echo "  wdr_tabstat                          display wdr table statistics"
    echo "  workload   [begin/end]               Collect workload information"
    echo "  xlogcom [START_WAL] [END_WAL]        analyze WAL commits per second"
    echo "  xloghc                               display xlog health check information"
    echo "  osw     [interval] [duration]        collect system performance data (default: interval=3s, duration=60s)"
    echo "  flamegraph [-p <pid>] [-s <seconds>] generate CPU flame graph (default: sample 10s)"
    echo ""
    echo "Options for analyze_log:"
    echo "  Usage: -f <file> [-b <begin>] [-e <end>] [-t <type>] [-o <output>]"
    echo "  Options:"
    echo "    -f: log file name (required)"
    echo "    -b: start time (optional)"
    echo "    -e: end time (optional)"
    echo "    -t: analysis type (plan or slow, default: slow)"
    echo "    -o: output format (html, csv, txt, default: html)"
    echo ""
    echo "Options for asp:"
    echo "  Usage: asp <type> -b <begin_time> -e <end_time>"
    echo "  Types:"
    echo "    cnt        active session count statistics"
    echo "    event      event analysis"
    echo "    waitchain  wait chain analysis"
    echo "    sql        running sql"
    echo "  Options:"
    echo "    -b: start time (format: 'YYYY-MM-DD HH24:MI:SS')"
    echo "    -e: end time (format: 'YYYY-MM-DD HH24:MI:SS')"
    echo ""
    echo "Options for dead_tups:"
    echo "  Usage: [-d <database>] [-s <schema>] [-t <table>]"
    echo "  Options:"
    echo "    -d: database name"
    echo "    -s: schema name"
    echo "    -t: table name"
    echo ""
    echo "Options for kill:"
    echo "  Usage: [OPTIONS] [SQL_OPTIONS]"
    echo "  Options:"
    echo "    -a              ALL Exclude background sessions"
    echo "    -d appname      Filter by application name"
    echo "    -i ip           Filter by client IP"
    echo "    -p pid          Filter by session ID"
    echo "    -q sqlid        Filter by unique SQL ID"
    echo "    -s state        Filter by session state"
    echo "    -t interval(s)  Filter transactions running longer than interval(seconds)"
    echo "    -u name         Filter by username"
    echo ""
    echo "Options for priv:"
    echo "  Usage: [-u <user>] [-d <database>] [-s <schema>] [-t <table>]"
    echo "  Options:"
    echo "    -u: user name"
    echo "    -d: database name"
    echo "    -s: schema name"
    echo "    -t: table name"
    echo ""
    echo "Options for tabsize:"
    echo "  Usage: -a <all> -n <top number>  or -d <database> -s <schema> -t <table> -n <top number>"
    echo "  Options:"
    echo "    -a: if need get tablesizes from all databases(optional, -a all)"
    echo "    -d: database name (optinal)"
    echo "    -s: schema name (optional)"
    echo "    -t: table name (optional)"
    echo "    -n: top number (required)"
    echo ""
    echo "Options for tabstat:"
    echo "  Usage: -d <database> -s <schema> -t <table>"
    echo "  Options:"
    echo "    -d: database name (default: postgres)"
    echo "    -s: schema name (required)"
    echo "    -t: table name (required)"
}

show_list() {
    echo "Vastbase Script Tool (vb_tool) v1.4.11"
    echo ""
    echo "Usage Summary:"
    echo "  vb_tool <command> [options]"
    echo "  Example: vb_tool as <vb_pid>"
    echo ""
    echo "Available Commands:"
    echo "  analyze_log                          analyze database logs (slow queries or plans)"
	echo "  analyze_log_v2                       analyze database logs (slow queries) output html report (enhanced version)"
    echo "  as       [vb pid]                    display active session info"
    echo "  asp                                  analyze active session profile"
    echo "  collect_log                          collect logs for cluster or single node"
    echo "  dead_tups                            display dead tuples information"
    echo "  index_check                          display redundant/unused/unusable/novalid index"
    echo "  kill                                 terminate sessions by conditions"
    echo "  list                                 list vb_tool available script"
    echo "  lockchain                            display lock wait chain"
    echo "  lock_details                         display detailed lock information (holders & waiters)"
    echo "  lsds                                 list block devices and metadata"
    echo "  mem                                  display memory usage information"
    echo "  memhist                              display memory usage history"
    echo "  net                                  display network information"
    echo "  priv                                 display privileges for users/tables/databases/schemas"
	echo "  planbyline [file]                    analyze execution plan and output self-time by line"
    echo "  recover_table                        recover table data by ctid scan (skip corrupted rows)"
    echo "  redo        -f <log_file>            analyze redo log generate"
    echo "  relxlog [START_WAL] [END_WAL]        analyze WAL records for relations"
    echo "  repl                                 display Streaming Replication lag"
    echo "  slow                                 display top slow sql Information"
    echo "  sp       [guc]                       display guc parameter"
    echo "  sqlstat  [unique_query_id]           display sqlstat information"
	echo "  sqltext  [unique_query_id]           display sqltext from postgresql slow log"
	echo "  sqlhc    [unique_query_id]           display sql health check(include performance plan & sqlstat & tabstat)"
    echo "  ssh_setup                            setup SSH connectivity between hosts"
    echo "  st       [relname]                   display dict table or view"
    echo "  tabsize                              display top number size of tables(including all indexes)"
    echo "  tabstat                              display table statistics"
    echo "  tps                                  analyze TPS per 10 minutes"
    echo "  wdr_event                            display wdr top event information"
    echo "  wdr_summary                          display wdr workload information"
    echo "  wdr_topsql                           display wdr topsql information"
    echo "  wdr_tabstat                          display wdr table statistics"
    echo "  workload   [begin/end]               Collect workload information"
    echo "  xlogcom [START_WAL] [END_WAL]        analyze WAL commits per second"
    echo "  xloghc                               display xlog health check information"
    echo "  osw     [interval] [duration]        collect system performance data (default: interval=3s, duration=60s)"
    echo "  flamegraph [-p <pid>] [-s <seconds>] generate CPU flame graph (default: sample 10s)"
    echo ""
}
